### PR TITLE
Use term ABB-free@home

### PR DESCRIPTION
**Pull request by kingsleyadam**
This is purely a documentation update.

- Updates any reference to the free@home brand to `Busch/ABB-free@home` to match-up with ABB branding. They seem to have two different namings, probably depending on region?
  - Internally I've just referenced ABB-free@home. The title of the integration and name in hacs as `Busch/ABB-free@home`.
  - https://www.busch-jaeger.nl/producten/systemen/busch-freehome
  - https://new.abb.com/low-voltage/products/building-automation/product-range/abb-freeathome

### CODE REVIEW

**Comment by derjoerg** [comment]
ABB is the "main" company behind this product and Busch-Jaeger is a sub-company of ABB, if I'm correct.

It can also be called `ABB/Busch-free@home`.

Another possibility would be to use the "virtual integration" feature https://developers.home-assistant.io/docs/creating_integration_manifest#virtual-integration
We have `ABB-free@home` and as virtual integration `Busch-free@home`

**Comment by derjoerg** [comment]
> Another possibility would be to use the "virtual integration" feature https://developers.home-assistant.io/docs/creating_integration_manifest#virtual-integration We have `ABB-free@home` and as virtual integration `Busch-free@home`

This would - for sure - also mean to have two integrations and also two brand files

**Review by derjoerg — COMMENTED** [review]
ABB is the "main" company behind this product and Busch-Jaeger is a sub-company of ABB, if I'm correct.

It can also be called `ABB/Busch-free@home`.

Another possibility would be to use the "virtual integration" feature https://developers.home-assistant.io/docs/creating_integration_manifest#virtual-integration
We have `ABB-free@home` and as virtual integration `Busch-free@home`
This would - for sure - also mean to have two integrations and also two brand files

**Comment by kingsleyadam** [comment]
> https://developers.home-assistant.io/docs/creating_integration_manifest#virtual-integration

I like the idea of a virtual integration. For this integration we can stick with `ABB-free@home` as that's the parent brand. Then a virtual integration can be added for `Busch-free@home`.

**Pull request merged**
