### PR TITLE
Adds new window position sensor

### PR DESCRIPTION
**Pull request by kingsleyadam**
This adds the window position sensor recently added to the PyPi package.

### CODE REVIEW

**Comment by kingsleyadam** [comment]
@nrenner73, can you test this?

The hassfest check is failing but the change should work. I'll have to work on the hassfest check.

**Comment by nrenner73** [comment]
A new device is showing up and it works!

image

Sensor 'Window Position' can be CLOSED, TILTED and OPEN
Sensor 'Window/Door' can be Open and Closed

which is great to work with.

Only issue is that i get a log warning entry:
```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:569
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 3:34:38 PM (1 occurrences)
Last logged: 3:34:38 PM

Entity sensor.wc_fenster_window_position (<class 'custom_components.abbfreeathome_ci.sensor.FreeAtHomeSensorEntity'>) is using state class 'measurement' which is impossible considering device class ('enum') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise report it to the author of the 'abbfreeathome_ci' custom integration
```

**Comment by kingsleyadam** [comment]
Did you also pull in the en.json changes? Looks like the translations are coming in.

You may also have to do a hard refresh of your browser, or open in incognito window.

I'll make an update to remove the log warning.

**Comment by nrenner73** [comment]
Yes, I also pulled the en.json changes. I just switched my HA to English.

In German it looks like this:
image

**Comment by kingsleyadam** [comment]
> German is as expected, as there isn't a German translation yet. I have this on my todo list

It's just bringing in the position value "TILTED" and not the translation "Tilted". But I expect these changes to fix that: https://github.com/kingsleyadam/local-abbfreeathome-hass/pull/46/commits/0028ccdb3c01b3c399fff365a5859983283704be

I've also now made a change to remove the state class so hopefully that error will go away, if you can confirm I'll merge this in and cut a new release.

https://github.com/kingsleyadam/local-abbfreeathome-hass/pull/46/commits/29d9b1f091c26c96a558bc1aa8fb23f0d3397b62

**Comment by nrenner73** [comment]
Log message is gone now, and sensor states look like this:
image

Perfect!

**Pull request merged**
